"""add_resolved_at_to_incidents

Revision ID: bd597ba8273f
Revises: 03cf23dee154
Create Date: 2026-04-20 20:14:17.740147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd597ba8273f'
down_revision: Union[str, Sequence[str], None] = '03cf23dee154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'resolved_at')
    # ### end Alembic commands ###
