"""add geo_enrichment_status to incidents

Revision ID: 5e04f019f70d
Revises: bd597ba8273f
Create Date: 2026-04-22 18:07:00.280190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e04f019f70d'
down_revision: Union[str, Sequence[str], None] = 'bd597ba8273f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('geo_enrichment_status', sa.Enum('pending', 'enriched', 'not_found', name='geoenrichmentstatus'), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'geo_enrichment_status')
    # ### end Alembic commands ###
