"""add_forest_name_to_incidents

Revision ID: 392fd382af9d
Revises: 5e04f019f70d
Create Date: 2026-05-01 23:40:09.492537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392fd382af9d'
down_revision: Union[str, Sequence[str], None] = '5e04f019f70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('forest_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'forest_name')
    # ### end Alembic commands ###
