"""add supervisor_name to incidents

Revision ID: 03cf23dee154
Revises: 685ded139b46
Create Date: 2026-04-20 17:55:30.977690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cf23dee154'
down_revision: Union[str, Sequence[str], None] = '685ded139b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('supervisor_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'supervisor_name')
    # ### end Alembic commands ###
