"""add_supervisor_fields_to_incidents

Revision ID: 685ded139b46
Revises: ef752849c265
Create Date: 2026-04-09 08:43:47.229121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685ded139b46'
down_revision: Union[str, Sequence[str], None] = 'ef752849c265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('supervisor_comment', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'supervisor_id')
    op.drop_column('incidents', 'supervisor_comment')
    # ### end Alembic commands ###
