"""added_cin_and_phone_number_to_users

Revision ID: 2a84ffdaf997
Revises: 
Create Date: 2026-04-19 23:46:55.526165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a84ffdaf997'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cin', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_users_cin', 'users', ['cin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_cin', 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'cin')
    # ### end Alembic commands ###
