"""supervisor_forest_many_to_many

Revision ID: 53ac04506665
Revises: 2a84ffdaf997
Create Date: 2026-05-03 23:29:43.074096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ac04506665'
down_revision: Union[str, Sequence[str], None] = '2a84ffdaf997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "supervisor_forest_assignments",
        sa.Column("user_id",   sa.Integer(), nullable=False),
        sa.Column("forest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "forest_id"),
    )
    # Migrate existing data from the old column before dropping it
    op.execute("""
        INSERT INTO supervisor_forest_assignments (user_id, forest_id)
        SELECT id, forest_id FROM users
        WHERE forest_id IS NOT NULL
    """)
    op.drop_column("users", "forest_id")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("forest_id", sa.Integer(), nullable=True))
    op.execute("""
        UPDATE users u
        SET forest_id = sfa.forest_id
        FROM supervisor_forest_assignments sfa
        WHERE sfa.user_id = u.id
    """)
    op.drop_table("supervisor_forest_assignments")
    # ### end Alembic commands ###
